kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: node:12.18.0-buster
    commands:
      - npm install
      - npm run build
    when:
      event: tag
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_api
      files:
        - dist/portx-win.exe
        - dist/portx-linux
        - dist/portx-macos
    when:
      event: tag
